### ISSUE TITLE
PureRotation can't run

### ISSUE THREAD

**Issue by gnpang** [MarineLasbleis/GrowYourIC#2]
I was trying to run the PureRotation class. I define the inner core radius with time as equal to rICB. However, when I try to evaluate the proxy, I always have a problem, please see the screenshot
![image](https://user-images.githubusercontent.com/11819121/98024567-b6f1e100-1dc5-11eb-835d-dab97124b635.png)

**Comment by MarineLasbleis** [comment]
For pure rotation, without growth,  the system can't calculate an age. So it is normal this does not converge, and you should use a different proxy.
